version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:14.1
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_PASSWORD=matheus
      - POSTGRES_USER=matheus
    ports:
    - "5432:5432"

